version: '3.8'

services:
    prisma-simple-app:
        build: .
        image: prisma-simple-nodejs
        container_name: prisma-simple-app
        env_file:
            - .env
        ports:
            - ${APP_PORT}:${APP_PORT}
        networks:
            - prismasimplenet

    prisma-simple-db:
        image: mysql:5.7
        container_name: prisma-simple-db
        environment:
            MYSQL_DATABASE: prisma_simple_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3232:3306
        networks:
            - prismasimplenet

networks:
  prismasimplenet:
      driver: bridge
